apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer-container
          image: michaelmonir2/micrepository:prod4

---

apiVersion: v1
kind: Service
metadata:
  name: producer-service
spec:
  selector:
    app: producer
  clusterIP: None
