apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: michaelmonir2/micrepository:prod4
          env:
            - name: KAFKA_SERVER
              value: kafka-service

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-service
spec:
  selector:
    app: kafka-producer
  ports:
    - name: producer-port
      protocol: TCP
      port: 8080  # Adjust the port as per your producer's configuration
      targetPort: 8080  # Adjust the targetPort as per your producer's configuration
